---

# Defines the JVM platform to use
# Choices are: `oracle` or `openjdk`
java_platform: "openjdk"

# Defines the verison of OpenJDK Java to install
# Options are: `1.6.0`, `1.7.0`, `1.8.0`, `11`
openjdk_java_version: ""

# Defines the version of Oracle Java to install
# You must have a corresponding vars file to match the version specified
# Example: "1.8.0_161"
oracle_java_version: ""

# The URL to the Oracle Java package you wish to download/install
# Obtain this URL from http://www.oracle.com/technetwork/java/javase/downloads/index.html
# and navigate to the Java version you want to download
# You'll need to accept the license agreement
# Then when you hover your mouse arrow over the download link, you'll see the download URL which you can copy/use
# Example: http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.rpm
oracle_java_url: "{{ 'http://pkgs.library.ucla.edu/oracle-java/jdk-8u201-linux-x64.rpm' if ansible_domain == 'library.ucla.edu' else 'https://download.oracle.com/otn-pub/java/jdk/8u201-b09/42970487e3af4f5aa5bca3f542482c60/jdk-8u201-linux-x64.rpm' }}"

# Obtain from the checksum page for this version of Oracle Java
java_rpm_md5: ""

# This split statement grabs the rpm filename off the end of the oracle_java_url
java_rpm_filename: ""

# Defines the path to the java home directory
# This determined by the JVM platform
java_home: ""
