---

#- name: Run OS-specific SCL repository setup
#  include_tasks: "{{ ansible_distribution }}_scl_repo_setup.yml"

- block:
  - name: Ensure SCL utility is installed
    yum:
      name: "scl-utils"
      state: present

  - name: Install SCL packages
    yum:
      name: "{{ item.pkg_name }}"
      state: "present"
    loop: "{{ scl_packages }}"

  - name: Enable SCL pacakges
    template:
      src: "enable_scl.j2"
      dest: "/etc/profile.d/enable{{ item.pkg_name }}.sh"
      owner: "root"
      group: "root"
      mode: 0644
    loop: "{{ scl_packages }}"
    when: item.scl_enable == "yes"
  when: scl_packages is defined
