---

# This allows for making the {{ project_name }}_{{ env_name }}.yml vars file optional.
# If this vars file is _not_ included in the role, the variables should be defined
# elsehwere - e.g. in the playbook file
#- name: Determine if the project-specific vars file exists
#  local_action:
#    module: stat
#    path: "{{ role_path }}/vars/{{ project_name }}_{{ env_name }}.yml"
#  register: project_vars_file

#- name: Set-up project-specific environment variables
#  include_vars: "{{ project_name }}_{{ env_name }}.yml"
#  when: project_vars_file.stat.exists
#  no_log: True

- name: Set-up the Capistrano environment
  include_tasks: 
    file: cap_setup.yml
    apply:
      tags:
        - cap-setup
  tags:
    - cap-setup

- name: Set-up the Sidekiq environment
  import_tasks: sidekiq_setup.yml
  tags:
    - sidekiq-setup

- name: Setup linked files (including dotenv)
  include_tasks: 
    file: linked_files_setup.yml
    apply:
      tags:
        - linked-file-setup
  when: lookup('vars', _project_name + '_linked_files', default = False )
  tags:
    - linked-file-setup
#- name: Set-up the dotenv environment variables file
#  import_tasks: dotenv_setup.yml
#  tags:
#    - dotenv-setup

- name: Set-up the rails application secret key
  import_tasks: rails_secretkey_setup.yml
  tags:
    - rails-secretkey-setup

- name: Set-up the ansible user's environment to run the deploy
  import_tasks: ansible_user_env_setup.yml
  tags:
    - ansible-user-env-setup

- name: Set-up the Apache HTTPD virtual host file
  import_tasks: apache_vhost_setup.yml
  tags:
    - apache-vhost-setup

- name: Set-up the rails application logrotate configuration
  import_tasks: logrotate_setup.yml
  tags:
    - logrotate-setup

- name: Execute the capistrano deploy process
  import_tasks: capistrano_deploy.yml
  tags:
    - capistrano-deploy
